<?php
$jieqiConfigs['obook'] = array (
  'staticurl' => '',
  'dynamicurl' => '',
  'topcachenum' => 10,
  'buychaptervip' => '',
  'obkstartx' => 20,
  'obkstarty' => 50,
  'obklinewidth' => 80,
  'obkfontsize' => 14,
  'obkfontjt' => 'C:/Windows/Fonts/simsun.ttc',
  'obkfontft' => 'C:/Windows/Fonts/simsun.ttc',
  'obkcharconvert' => '1',
  'obkimagetype' => 'txt',
  'jpegquality' => 90,
  'obkimagecolor' => '#ffffff',
  'obktextcolor' => '#000000',
  'obkangle' => 0,
  'obkshadowcolor' => '#000000',
  'obkshadowdeep' => 0,
  'obkwatertext' => '0',
  'obkwaterformat' => '',
  'obkwatercolor' => '#ff6600',
  'obkwatersize' => 16,
  'obkwaterangle' => 45,
  'obkwaterpct' => 30,
  'obookwater' => '0',
  'obookwimage' => 'watermark.gif',
  'obookwtrans' => 30,
  'obookreadhead' => '',
  'obookreadfoot' => '     
     本书是免费读书原创首发，禁止转载。请支持原创，支持正版！免费读书(www.mianfeidushu.com)版权所有，侵权必究。关注官方微信号:免费读书（mianfeidushu）,每天给您推荐最热门书籍。',
  'wordsperegold' => 125,
  'priceround' => '0',
);

?>
