<?php
$jieqiAction['article'] = array (
  'articleadd' => 
  array (
    'acttitle' => '发表新作',
    'minscore' => '0',
    'islog' => '0',
    'isreview' => '0',
    'isvip' => '0',
    'ismessage' => '1',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '200',
    'earncredit' => '200',
    'earnvipvote' => '0',
  ),
  'chapteradd' => 
  array (
    'acttitle' => '增加章节',
    'minscore' => '0',
    'islog' => '0',
    'isreview' => '0',
    'isvip' => '0',
    'ismessage' => '0',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '10',
    'earncredit' => '10',
    'earnvipvote' => '0',
  ),
  'reviewadd' => 
  array (
    'acttitle' => '发表书评',
    'minscore' => '0',
    'islog' => '0',
    'isreview' => '0',
    'isvip' => '0',
    'ismessage' => '1',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '50',
    'earncredit' => '20',
    'earnvipvote' => '0',
  ),
  'reviewgood' => 
  array (
    'acttitle' => '书评精华',
    'minscore' => '0',
    'islog' => '0',
    'isreview' => '0',
    'isvip' => '0',
    'ismessage' => '1',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '10',
    'earncredit' => '100',
    'earnvipvote' => '0',
  ),
  'replyadd' => 
  array (
    'acttitle' => '发表回复',
    'minscore' => '0',
    'islog' => '0',
    'isreview' => '0',
    'isvip' => '0',
    'ismessage' => '1',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '30',
    'earncredit' => '10',
    'earnvipvote' => '0',
  ),
  'rate' => 
  array (
    'acttitle' => '小说评分',
    'minscore' => '0',
    'islog' => '0',
    'isreview' => '0',
    'isvip' => '0',
    'ismessage' => '0',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '30',
    'earncredit' => '20',
    'earnvipvote' => '0',
  ),
  'poll' => 
  array (
    'acttitle' => '小说推荐',
    'minscore' => '0',
    'islog' => '0',
    'isreview' => '0',
    'isvip' => '0',
    'ismessage' => '0',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '50',
    'earncredit' => '50',
    'earnvipvote' => '0',
  ),
  'down' => 
  array (
    'acttitle' => '小说下载',
    'minscore' => '0',
    'islog' => '0',
    'isreview' => '0',
    'isvip' => '0',
    'ismessage' => '0',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '10',
    'earncredit' => '10',
    'earnvipvote' => '0',
  ),
  'flower' => 
  array (
    'acttitle' => '投鲜花',
    'minscore' => '0',
    'islog' => '1',
    'isreview' => '1',
    'isvip' => '1',
    'ismessage' => '1',
    'ispay' => '1',
    'paytitle' => '鲜花',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '50',
    'earncredit' => '100',
    'earnvipvote' => '0',
  ),
  'egg' => 
  array (
    'acttitle' => '扔鸡蛋',
    'minscore' => '0',
    'islog' => '1',
    'isreview' => '1',
    'isvip' => '1',
    'ismessage' => '0',
    'ispay' => '1',
    'paytitle' => '鸡蛋',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '10',
    'earncredit' => '100',
    'earnvipvote' => '0',
  ),
  'vipvote' => 
  array (
    'acttitle' => '送月票',
    'minscore' => '0',
    'islog' => '1',
    'isreview' => '1',
    'isvip' => '1',
    'ismessage' => '1',
    'ispay' => '1',
    'paytitle' => '月票',
    'paybase' => 1,
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '10',
    'earncredit' => '100',
    'earnvipvote' => '0',
  ),
  'tip' => 
  array (
    'acttitle' => '打赏',
    'minscore' => '0',
    'islog' => '1',
    'isreview' => '1',
    'isvip' => '1',
    'ismessage' => '1',
    'ispay' => '1',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '20',
    'paymax' => '0',
    'earnscore' => '80',
    'earncredit' => '10',
    'earnvipvote' => '0',
  ),
  'hurry' => 
  array (
    'acttitle' => '催更',
    'minscore' => '0',
    'islog' => '1',
    'isreview' => '1',
    'isvip' => '1',
    'ismessage' => '1',
    'ispay' => '1',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '20',
    'paymax' => '0',
    'earnscore' => '100',
    'earncredit' => '50',
    'earnvipvote' => '0',
  ),
  'buychapter' => 
  array (
    'acttitle' => '订阅章节',
    'minscore' => '0',
    'islog' => '1',
    'isreview' => '0',
    'isvip' => '1',
    'ismessage' => '0',
    'ispay' => '1',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '20',
    'paymax' => '0',
    'earnscore' => '200',
    'earncredit' => '200',
    'earnvipvote' => '0',
  ),
  'bookcase' => 
  array (
    'acttitle' => '小说收藏',
    'minscore' => '0',
    'islog' => '1',
    'isreview' => '0',
    'isvip' => '1',
    'ismessage' => '0',
    'ispay' => '1',
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => '20',
    'paymax' => '0',
    'earnscore' => '80',
    'earncredit' => '100',
    'earnvipvote' => '0',
  ),
  //burn 添加，2016-12-09
  'redrose' =>
	  array (
		'acttitle' => '赏红包',
		'minscore' => '0',
		'islog' => '1',
		'isreview' => '1',
		'isvip' => '1',
		'ismessage' => '1',
		'ispay' => '1',
		'paytitle' => '红包',
		'paybase' => 1,
		'paymin' => '0',
		'paymax' => '0',
		'earnscore' => '50',
		'earncredit' => '100',
		'earnvipvote' => '0',
	),
'yellowrose' =>
	array (
		'acttitle' => '赏美酒',
		'minscore' => '0',
		'islog' => '1',
		'isreview' => '1',
		'isvip' => '1',
		'ismessage' => '1',
		'ispay' => '1',
		'paytitle' => '美酒',
		'paybase' => 1,
		'paymin' => '0',
		'paymax' => '0',
		'earnscore' => '50',
		'earncredit' => '100',
		'earnvipvote' => '0',
	),
'bluerose' =>
	array (
		'acttitle' => '赏香囊',
		'minscore' => '0',
		'islog' => '1',
		'isreview' => '1',
		'isvip' => '1',
		'ismessage' => '1',
		'ispay' => '1',
		'paytitle' => '香囊',
		'paybase' => 1,
		'paymin' => '0',
		'paymax' => '0',
		'earnscore' => '50',
		'earncredit' => '100',
		'earnvipvote' => '0',
	),
'whiterose' =>
	array (
		'acttitle' => '赏钻石',
		'minscore' => '0',
		'islog' => '1',
		'isreview' => '1',
		'isvip' => '1',
		'ismessage' => '1',
		'ispay' => '1',
		'paytitle' => '钻石',
		'paybase' => 1,
		'paymin' => '0',
		'paymax' => '0',
		'earnscore' => '50',
		'earncredit' => '100',
		'earnvipvote' => '0',
	),
'blackrose' =>
	array (
		'acttitle' => '赏跑车',
		'minscore' => '0',
		'islog' => '1',
		'isreview' => '1',
		'isvip' => '1',
		'ismessage' => '1',
		'ispay' => '1',
		'paytitle' => '跑车',
		'paybase' => 1,
		'paymin' => '0',
		'paymax' => '0',
		'earnscore' => '50',
		'earncredit' => '100',
		'earnvipvote' => '0',
	),
'greenrose' =>
	array (
		'acttitle' => '赏皇冠',
		'minscore' => '0',
		'islog' => '1',
		'isreview' => '1',
		'isvip' => '1',
		'ismessage' => '1',
		'ispay' => '1',
		'paytitle' => '皇冠',
		'paybase' => 1,
		'paymin' => '0',
		'paymax' => '0',
		'earnscore' => '50',
		'earncredit' => '100',
		'earnvipvote' => '0',
	)
);

?>