<?php
$jieqiConfigs['article'] = array (
	'indexprows' => 0,
	'pagenum' => 30,
	'wappagenum' => 10,
	'cachenum' => 10,
	'topcachenum' => 10,
	'reviewwidth' => 90,
	'maxreviewsize' => 0,
	'minreviewsize' => 0,
	'goodreviewpercent' => 10,
	'reviewenter' => '1',
	'maxbookmarks' => 100,
	'maxmarkclass' => 20,
	'textwatermark' => '',
	'pageimagecode' => '<div class=\\\\\\"divimage\\\\\\"><img src=\\\\\\"<{$imageurl}>\\\\\\" border=\\\\\\"0\\\\\\" class=\\\\\\"imagecontent\\\\\\"></div>',
	'txtarticlehead' => '',
	'txtarticlefoot' => '支持正版，支持免费读书网，更多内容请点击：www.mianfeidushu.com',
	'authtypeset' => '1',
	'autotypeset' => '1',
	'searchtype' => '0',
	'minsearchlen' => 2,
	'maxsearchres' => 300,
	'minsearchtime' => 5,
	'checkappwriter' => '1',
	'articlevote' => '0',
	'writergroup' => '专栏作家',
	'samearticlename' => '0',
	'visitstatnum' => 13,
	'eachlinknum' => 0,
	'maketxt' => '1',
//	'txtdir' => 'C:\\\\virtualhost\\\\bacoolread\\\\files\\\\article\\\\txt',
	'txtdir' => 'E:\\\\files\\\\article\\\\txt',
	'txturl' => 'http://pic.kyread.com/txt',
	'makeopf' => '1',
//	'opfdir' => 'C:\\\\virtualhost\\\\bacoolread\\\\files\\\\article\\\\txt',
	'opfdir' => 'E:\\\\files\\\\article\\\\txt',
	'opfurl' => 'http://pic.kyread.com/txt',
	'maketxtjs' => '0',
	'usetxtjs' => '0',
	'txtjsdir' => 'js',
	'txtjsurl' => '',
	'makehtml' => '0',
	'htmldir' => 'html',
	'htmlurl' => '',
	'htmlfile' => '.html',
	'makefull' => '0',
	'fulldir' => 'fulltext',
	'fullurl' => '',
	'makezip' => '0',
	'zipdir' => 'zip',
	'zipurl' => '',
	'maketxtfull' => '1',
	'txtfulldir' => 'txtfull',
	'txtfullurl' => '',
	'makeumd' => 0,
	'umddir' => 'umd',
	'umdurl' => '',
	'makejar' => 0,
	'jardir' => 'jar',
	'jarurl' => '',
	//'imagedir' => 'C:\\\\virtualhost\\\\bacoolread\\\\files\\\\article\\\\image',
	'imagedir' => 'E:\\\\files\\\\article\\\\image',
	'imagetype' => '.jpg',
	'imageurl' => 'http://pic.kyread.com/image',
	'coverwidth' => 204,
	'coverheight' => 255,
	'coverlwidth' => 568,
	'coverlheight' => 312,
	'fakeinfo' => '/info/<{$id}>.html',
	'fakebookcase' => '',
	'fakeread' => '/read_<{$id}>.html',
	'fakesort' => '/sort/<{$sortcode}>/<{$page}>.html',
	'fakefullsort' => '/fullsort/<{$sortcode}>/<{$page}>.html',
	'fakeinitial' => '/initial/<{$initial}>/<{$page}>.html',
	'faketoplist' => '/top/<{$order}>/<{$page}>.html',
	'fakefulltop' => '/fulltop/<{$order}>/<{$page}>.html',
	'fakefilter' => '',
	'fakearticle' => '',
	'fakechapter' => '',
	'fakechaptervip' => '',
	'fakeshow' => '/news/<{$id}>.html',
	'fakeauthor' => '/author/<{$id}>.html',
	'staticurl' => '',
	'dynamicurl' => '',
	'maxrates' => 10,
	'dayrates' => 10,
	'dayvotes' => 10,
	'voteminsize' => 0,
	'monthlys' => '1、必须是VIP作品，如果不是，请先申请VIP.<br/>
2、必须是签约作品。<br/>
3、必须是网站活动期间申请！<br/>',
	'monthlysize' => 50000,
	'vipbook' => '1、字数大于50000.<br/>
2、必须是签约作品。<br/>
3、必须是网站活动期间申请！<br/>',
	'vipsize' => 50000,
	'jings' => '1、字数大于50000.<br/>
2、必须是签约作品。<br/>
3、必须是网站活动期间申请！<br/>',
	'jingsize' => 50000,
	'fengmian' => ' <li><strong>重磅图推介绍：</strong></li>
<li>重磅推荐是独立于免费读书网热推、封推、分类推等之外的一个推荐，审核的过程十分严格，注重剧情和文笔，本着宁缺毋滥的原则，在首页推荐榜单中最具权威性。</li>
<li><strong>重磅图推申请标准：</strong></li>
<li>1、	申请作品不涉及政治，色情问题，在免费读书网网站发表字数需五万字以上。</li>
<li>2、	诗歌散文和短篇小说不在申请推荐行列中，每部作品原则上只推荐一次。</li>
<li>3、	重磅图推申请不考虑作品点击与推荐票方面的数据，只看文章质量；首先文字品质要求较高，语句要求通顺，具有一定文字功力；其次情节生动精彩，最好在创意与新意方面有所突出，能吸引读者的阅读欲望；人物性格鲜明，能令读者留下深刻印象。</li>
<li>4、	每部作品只接受一次申请，重复申请无效，编辑对一部作品的申请也只会回复一次，请勿一周内多次重复申请。</li>
<li>5、	重磅图推主要面对免费读书网签约作品，对于其他网站的VIP作品，我们不进行推荐，同时如果出现在重磅图推期间成为其他网站VIP的情况，我们有权立刻将违规作品撤下推荐。</li>
<li><strong>重磅图推过程：</strong></li>
<li>1、	作者申请重磅图推后，将由网站编辑立刻进行审核，对于每部作品仅回复一次，审核时间在一周以内。</li>
<li>2、	审核通过的作品需提供五千字的存稿并日更新不低于三千字，若期间有断更现象，立即撤下推荐，并将直接影响下本书的推荐申请。</li>
<li>3、	推荐时间长达七天。</li>',
	'fengmiansize' => 50000,
	'qianyue' => '1、字数大于30000.<br/>
2、必须是原创作品，不得带有违反国家法律相关的言语<br/>
3.将您的个人资料准备好，申请以后管理员会联系你，然后将个人资料发给管理员<br/>',
	'vip' => '1、若您的小说达到本站上架标准，且作者是本站签约作者，则可以申请上架！<br/>
',
	'vipvote' => 500,
	'flower' => 10,
	'egg' => 10,
	'experience' => 100000,
	'vipvotenums' => 5,
	'vipvoteegold' => 500,
	'needcheck' => '1',
	'splitwords' => 5000,
	'maxwords' => 20000,
	'minwords' => 50,
	'maxsize' => 2048000,
	'minsize' => 0,
	'uploaddir' => 'upload',
	'postdenywords' => '',
	'redrose' => 100,
	'yellowrose' => 500,
	'bluerose' => 1000,
	'whiterose' => 5000,
	'blackrose' => 10000,
	'greenrose' => 100000,
	'attachdir' => 'attachment',
	'attachtype' => 'gif jpg jpeg png bmp swf',
	'maxattachnum' => 0,
	'maximagesize' => 1000,
	'maxfilesize' => 1000,
	'attachurl' => '',
	'attachwater' => '0',
	'attachwimage' => 'watermark.gif',
	'attachwtrans' => 30,
	'attachwquality' => 90,
);

?>