<?php
$jieqiBlocks['1'] = array (
  'bid' => 0,
  'blockname' => '鲜花周榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allflower,10,0,0,0,0',
  'template' => 'shuku.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['2'] = array (
  'bid' => 0,
  'blockname' => '推荐周榜单订',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'postdate,10,0,0,0,0',
  'template' => 'shuku.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['3'] = array (
  'bid' => 0,
  'blockname' => '推荐周榜包月',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'postdate,10,0,0,0,0',
  'template' => 'shuku.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['4'] = array (
  'bid' => 0,
  'blockname' => '新书签约单订',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'postdate,10,0,0,0,0',
  'template' => 'shuku.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['5'] = array (
  'bid' => 0,
  'blockname' => '新书签约包月',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'postdate,10,0,0,0,0',
  'template' => 'shuku.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
?>