<?php
$jieqiCollect = array (
  'sitename' => '91shenshu',
  'siteurl' => 'http://www.91shenshu.com/',
  'subarticleid' => '',
  'subchapterid' => '',
  'proxy_host' => '',
  'proxy_port' => '',
  'autoclear' => '0',
  'defaultfull' => '0',
  'referer' => '0',
  'pagecharset' => 'auto',
  'urlarticle' => 'http://www.91shenshu.com/info/<{articleid}>.html',
  'articletitle' => 
  array (
    'left' => '<h2>',
    'right' => '</h2>',
    'middle' => '!!!!',
  ),
  'author' => 
  array (
    'left' => '<strong>',
    'right' => '</strong>',
    'middle' => '!!!!',
  ),
  'sort' => 
  array (
    'left' => '<span class="cate"><a>',
    'right' => '</a></span>',
    'middle' => '!!!!',
  ),
  'keyword' => '',
  'intro' => 
  array (
    'left' => '<pre class="note">',
    'right' => '</pre>
	    	        		           <pre class="note"></pre>',
    'middle' => '****',
  ),
  'articleimage' => 
  array (
    'left' => 'index.html"> <img src="',
    'right' => '" alt="',
    'middle' => '~~~~',
  ),
  'filterimage' => '',
  'indexlink' => '',
  'fullarticle' => '',
  'sortid' => 
  array (
    '玄幻' => '1',
    '奇幻' => '1',
    '魔法' => '1',
    '魔幻' => '1',
    '玄幻魔法' => '1',
    '奇幻玄幻' => '1',
    '玄幻小说' => '1',
    '玄幻·魔幻' => '1',
    '玄幻异界' => '1',
    '玄幻奇幻' => '1',
    '武侠' => '2',
    '仙侠' => '2',
    '武侠小说' => '2',
    '武侠仙侠' => '2',
    '仙侠武侠' => '2',
    '修真' => '2',
    '修真小说' => '2',
    '仙侠小说' => '2',
    '武侠修真' => '2',
    '仙侠修真' => '2',
    '都市' => '3',
    '言情' => '3',
    '都市小说' => '3',
    '言情小说' => '3',
    '现代都市' => '3',
    '都市言情' => '3',
    '都市异能' => '3',
    '浪漫言情' => '3',
    '都市.生活' => '3',
    '言情.校园' => '3',
    '历史' => '4',
    '军事' => '4',
    '历史小说' => '4',
    '军事小说' => '4',
    '架空' => '4',
    '历史军事' => '4',
    '军事历史' => '4',
    '架空历史' => '4',
    '社会.历史' => '4',
    '穿越小说' => '4',
    '网游小说' => '5',
    '竞技小说' => '5',
    '网游' => '5',
    '竞技' => '5',
    '动漫' => '5',
    '动漫小说' => '5',
    '游戏' => '5',
    '网游动漫' => '5',
    '网游竞技' => '5',
    '游戏竞技' => '5',
    '科幻' => '6',
    '科幻小说' => '6',
    '军事科幻' => '6',
    '科幻灵异' => '6',
    '异术超能' => '6',
    '灵异' => '7',
    '灵异小说' => '7',
    '恐怖' => '7',
    '恐怖小说' => '7',
    '恐怖灵异' => '7',
    '灵异恐怖' => '7',
    '恐怖.奇幻' => '7',
    '奇幻小说' => '7',
    '悬疑小说' => '7',
    '剧本' => '8',
    '其他' => '8',
    '其他小说' => '8',
    '名著' => '8',
    '其他类型' => '8',
    '名家名著' => '8',
    '美文名著' => '8',
    '出版书籍' => '8',
    '综合其他' => '8',
    '经典名著' => '8',
    '同人漫画' => '8',
    '青春小说' => '8',
    '校园小说' => '8',
    '同人小说' => '8',
    '经典小说' => '8',
    '畅销小说' => '8',
  ),
  'urlindex' => 'http://www.91shenshu.com/book/0/<{articleid}>/index.html',
  'volume' => '',
  'chapter' => 
  array (
    'left' => 'class="name">',
    'right' => '</a>
		</li>',
    'middle' => '!!!!',
  ),
  'chapterid' => 
  array (
    'left' => '<a href="http://www.91shenshu.com/book/$/$/',
    'right' => '.html" class="name">',
    'middle' => '$$$$',
  ),
  'urlchapter' => 'http://www.91shenshu.com/book/0/<{articleid}>/<{chapterid}>.html',
  'content' => 
  array (
    'left' => 'ChapterContent924915">',
    'right' => '</div>',
    'middle' => '****',
  ),
  'contentfilter' => '</p><br/>',
  'contentreplace' => '',
  'collectimage' => '1',
  'imagetranslate' => '0',
  'addimagewater' => '0',
  'imagebgcolor' => '',
  'imageareaclean' => '',
  'imagecolorclean' => '',
  'listcollect' => '',
);
?>